use sqlx::{PgPool, Result};
use uuid::Uuid;

use crate::models::{QuestionRating, RatingEvent, UserRating};

const USER_RATING_BY_USER_ID: &str = r#"
    SELECT
        user_id,
        rating,
        games_played,
        wins,
        losses,
        draws,
        created_at,
        updated_at
    FROM user_ratings
    WHERE user_id = $1
"#;

const QUESTION_RATING_BY_QUESTION_ID: &str = r#"
    SELECT
        question_id,
        rating,
        attempts,
        correct_answers,
        created_at,
        updated_at
    FROM question_ratings
    WHERE question_id = $1
"#;

const RATING_EVENTS_BY_USER_ID: &str = r#"
    SELECT
        id,
        attempt_id,
        user_id,
        question_id,
        source_type,
        source_id,
        quiz_type,
        outcome,
        correct,
        zone,
        error_pct,
        k,
        sa,
        point_delta,
        user_rating_before,
        user_rating_after,
        player_elo_before,
        player_elo_after,
        question_rating_before,
        question_rating_after,
        question_elo_before,
        question_elo_after,
        rating_delta,
        created_at
    FROM rating_events
    WHERE user_id = $1
    ORDER BY created_at DESC, id DESC
    LIMIT $2
    OFFSET $3
"#;

const RATING_EVENTS_BY_QUESTION_ID: &str = r#"
    SELECT
        id,
        attempt_id,
        user_id,
        question_id,
        source_type,
        source_id,
        quiz_type,
        outcome,
        correct,
        zone,
        error_pct,
        k,
        sa,
        point_delta,
        user_rating_before,
        user_rating_after,
        player_elo_before,
        player_elo_after,
        question_rating_before,
        question_rating_after,
        question_elo_before,
        question_elo_after,
        rating_delta,
        created_at
    FROM rating_events
    WHERE question_id = $1
    ORDER BY created_at DESC, id DESC
    LIMIT $2
    OFFSET $3
"#;

const RATING_EVENTS_BY_ATTEMPT_ID: &str = r#"
    SELECT
        id,
        attempt_id,
        user_id,
        question_id,
        source_type,
        source_id,
        quiz_type,
        outcome,
        correct,
        zone,
        error_pct,
        k,
        sa,
        point_delta,
        user_rating_before,
        user_rating_after,
        player_elo_before,
        player_elo_after,
        question_rating_before,
        question_rating_after,
        question_elo_before,
        question_elo_after,
        rating_delta,
        created_at
    FROM rating_events
    WHERE attempt_id = $1
    ORDER BY created_at ASC, id ASC
"#;

/// Returns the user's current Elo row, if it exists.
pub async fn user_rating_by_user_id(pool: &PgPool, user_id: Uuid) -> Result<Option<UserRating>> {
    sqlx::query_as::<_, UserRating>(USER_RATING_BY_USER_ID)
        .bind(user_id)
        .fetch_optional(pool)
        .await
}

/// Returns the question's current Elo row, if it exists.
pub async fn question_rating_by_question_id(
    pool: &PgPool,
    question_id: Uuid,
) -> Result<Option<QuestionRating>> {
    sqlx::query_as::<_, QuestionRating>(QUESTION_RATING_BY_QUESTION_ID)
        .bind(question_id)
        .fetch_optional(pool)
        .await
}

/// Returns newest-first user rating audit history.
pub async fn rating_events_by_user_id(
    pool: &PgPool,
    user_id: Uuid,
    limit: i64,
    offset: i64,
) -> Result<Vec<RatingEvent>> {
    sqlx::query_as::<_, RatingEvent>(RATING_EVENTS_BY_USER_ID)
        .bind(user_id)
        .bind(limit)
        .bind(offset)
        .fetch_all(pool)
        .await
}

/// Returns newest-first question rating audit history.
pub async fn rating_events_by_question_id(
    pool: &PgPool,
    question_id: Uuid,
    limit: i64,
    offset: i64,
) -> Result<Vec<RatingEvent>> {
    sqlx::query_as::<_, RatingEvent>(RATING_EVENTS_BY_QUESTION_ID)
        .bind(question_id)
        .bind(limit)
        .bind(offset)
        .fetch_all(pool)
        .await
}

/// Returns newest-first rating history for a user.
pub async fn rating_history_by_user_id(
    pool: &PgPool,
    user_id: Uuid,
    limit: i64,
    offset: i64,
) -> Result<Vec<RatingEvent>> {
    rating_events_by_user_id(pool, user_id, limit, offset).await
}

/// Returns newest-first rating history for a question.
pub async fn rating_history_by_question_id(
    pool: &PgPool,
    question_id: Uuid,
    limit: i64,
    offset: i64,
) -> Result<Vec<RatingEvent>> {
    rating_events_by_question_id(pool, question_id, limit, offset).await
}

/// Returns all rating events generated by one atomic attempt.
pub async fn rating_events_by_attempt_id(
    pool: &PgPool,
    attempt_id: Uuid,
) -> Result<Vec<RatingEvent>> {
    sqlx::query_as::<_, RatingEvent>(RATING_EVENTS_BY_ATTEMPT_ID)
        .bind(attempt_id)
        .fetch_all(pool)
        .await
}

// Short aliases keep the query module pleasant to use from repositories.
pub async fn find_user_rating(pool: &PgPool, user_id: Uuid) -> Result<Option<UserRating>> {
    user_rating_by_user_id(pool, user_id).await
}

/// Returns the current Elo row for a user, if one has been initialized.
pub async fn get_user_rating(pool: &PgPool, user_id: Uuid) -> Result<Option<UserRating>> {
    user_rating_by_user_id(pool, user_id).await
}

pub async fn find_question_rating(
    pool: &PgPool,
    question_id: Uuid,
) -> Result<Option<QuestionRating>> {
    question_rating_by_question_id(pool, question_id).await
}

/// Returns the current Elo row for a question, if one has been initialized.
pub async fn get_question_rating(
    pool: &PgPool,
    question_id: Uuid,
) -> Result<Option<QuestionRating>> {
    question_rating_by_question_id(pool, question_id).await
}
