[package]
name = "orion-redis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
fred = { workspace = true, features = ["i-scripts"] }
orion-common.workspace = true
orion-db.workspace = true
orion-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
